import { AdminProfile, CoordinatorAssignment, EventItem, Team, TeamMember, AttendanceRecord, EventRegistration } from '../types/database';

export const MOCK_ADMIN_PROFILES: AdminProfile[] = [
  {
    id: 'usr-super-01',
    roll_no: 'ADMIN01',
    full_name: 'Dr. R. Vignesh (Super Admin)',
    role: 'SUPER_ADMIN',
    is_active: true,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'usr-tech-overall-02',
    roll_no: 'TECH01',
    full_name: 'Kavin Raj (Overall Tech Lead)',
    role: 'COORDINATOR',
    is_active: true,
    created_at: '2026-01-02T00:00:00Z',
  },
  {
    id: 'usr-tech-event-03',
    roll_no: 'TECH02',
    full_name: 'Priya Dharshini (Debugging Coord)',
    role: 'COORDINATOR',
    is_active: true,
    created_at: '2026-01-03T00:00:00Z',
  },
  {
    id: 'usr-nontech-overall-04',
    roll_no: 'NONTECH01',
    full_name: 'Divya Bharathi (Overall Non-Tech Lead)',
    role: 'COORDINATOR',
    is_active: true,
    created_at: '2026-01-04T00:00:00Z',
  },
  {
    id: 'usr-nontech-film-05',
    roll_no: 'NONTECH02',
    full_name: 'Arun Vijay (Short Film Coord)',
    role: 'COORDINATOR',
    is_active: true,
    created_at: '2026-01-05T00:00:00Z',
  },
  {
    id: 'usr-food-06',
    roll_no: 'FOODC01',
    full_name: 'Suresh Babu (Food Committee Head)',
    role: 'FOOD_STAFF',
    is_active: true,
    created_at: '2026-01-06T00:00:00Z',
  },
  {
    id: 'usr-food-07',
    roll_no: 'FOODC02',
    full_name: 'Rajesh Kumar (Food Counter 2)',
    role: 'FOOD_STAFF',
    is_active: true,
    created_at: '2026-01-06T00:00:00Z',
  },
  {
    id: 'usr-gate-08',
    roll_no: 'GATE01',
    full_name: 'Karthik Raja (Gate Check-in Staff)',
    role: 'GATE_STAFF',
    is_active: true,
    created_at: '2026-01-07T00:00:00Z',
  },
  {
    id: 'usr-inactive-09',
    roll_no: 'BLOCK01',
    full_name: 'Suspended Volunteer (Inactive)',
    role: 'VOLUNTEER',
    is_active: false,
    created_at: '2026-01-09T00:00:00Z',
  }
];

export const MOCK_ASSIGNMENTS: CoordinatorAssignment[] = [
  // Super Admin has all access
  {
    id: 'asg-01',
    admin_id: 'usr-super-01',
    assignment_type: 'OVERALL_TECH',
    event_id: null,
  },
  {
    id: 'asg-02',
    admin_id: 'usr-tech-overall-02',
    assignment_type: 'OVERALL_TECH',
    event_id: null,
  },
  {
    id: 'asg-03',
    admin_id: 'usr-tech-event-03',
    assignment_type: 'TECH_EVENT',
    event_id: 'debugging',
  },
  {
    id: 'asg-04',
    admin_id: 'usr-nontech-overall-04',
    assignment_type: 'OVERALL_NON_TECH',
    event_id: null,
  },
  {
    id: 'asg-05',
    admin_id: 'usr-nontech-film-05',
    assignment_type: 'NON_TECH_EVENT',
    event_id: 'short-flim',
  },
  {
    id: 'asg-06',
    admin_id: 'usr-food-06',
    assignment_type: 'FOOD',
    event_id: null,
  },
  {
    id: 'asg-07',
    admin_id: 'usr-food-07',
    assignment_type: 'FOOD',
    event_id: null,
  },
  {
    id: 'asg-08',
    admin_id: 'usr-gate-08',
    assignment_type: 'GATE_ENTRY',
    event_id: null,
  }
];

export const MOCK_EVENTS: EventItem[] = [
  {
    id: 'debugging',
    code: '01',
    mission_name: 'DEBUGGING',
    title: 'Debugging',
    event_type: 'TECH',
    category: 'TECHNICAL',
    clearance_level: 'ALL',
    team_size_min: 1,
    team_size_max: 2,
    venue: 'CSE Lab 1',
    schedule_time: '10:00 AM - 11:30 AM',
    duration: '90 Mins',
    description: 'Code debugging challenge',
    status: 'AVAILABLE',
  },
  {
    id: 'the-last-signal',
    code: '02',
    mission_name: 'THE LAST SIGNAL',
    title: 'The Last Signal',
    event_type: 'TECH',
    category: 'TECHNICAL',
    clearance_level: 'ALL',
    team_size_min: 1,
    team_size_max: 2,
    venue: 'CSE Seminar Hall',
    schedule_time: '11:30 AM - 01:00 PM',
    duration: '90 Mins',
    description: 'Cryptic network signal tracing',
    status: 'AVAILABLE',
  },
  {
    id: 'lost-at-sql',
    code: '03',
    mission_name: 'LOST AT SQL',
    title: 'Lost at SQL',
    event_type: 'TECH',
    category: 'TECHNICAL',
    clearance_level: 'ALL',
    team_size_min: 1,
    team_size_max: 2,
    venue: 'CSE Lab 2',
    schedule_time: '10:00 AM - 11:30 AM',
    duration: '90 Mins',
    description: 'Relational DB puzzle solving',
    status: 'AVAILABLE',
  },
  {
    id: 'gadget-codes',
    code: '04',
    mission_name: 'GADGET CODES',
    title: 'Gadget Codes',
    event_type: 'TECH',
    category: 'TECHNICAL',
    clearance_level: 'ALL',
    team_size_min: 1,
    team_size_max: 2,
    venue: 'IoT Center',
    schedule_time: '02:00 PM - 03:30 PM',
    duration: '90 Mins',
    description: 'Hardware programming and circuit hacking',
    status: 'AVAILABLE',
  },
  {
    id: 'paper-presentation',
    code: '05',
    mission_name: 'PAPER PRESENTATION',
    title: 'Paper Presentation',
    event_type: 'TECH',
    category: 'TECHNICAL',
    clearance_level: 'ALL',
    team_size_min: 1,
    team_size_max: 2,
    venue: 'Auditorium Hall B',
    schedule_time: '10:00 AM - 01:00 PM',
    duration: '180 Mins',
    description: 'Technical research paper presentation',
    status: 'AVAILABLE',
  },
  {
    id: 'borderland-at-gcee',
    code: '06',
    mission_name: 'BORDERLAND AT GCEE',
    title: 'Borderland at GCEE',
    event_type: 'NON_TECH',
    category: 'NON_TECHNICAL',
    clearance_level: 'ALL',
    team_size_min: 1,
    team_size_max: 2,
    venue: 'Campus Quadrangle',
    schedule_time: '02:00 PM - 04:00 PM',
    duration: '120 Mins',
    description: 'Real-world campus survival & tactical quest',
    status: 'AVAILABLE',
  },
  {
    id: 'think-strike-and-win',
    code: '07',
    mission_name: 'THINK, STRIKE AND WIN',
    title: 'Think, Strike and Win',
    event_type: 'NON_TECH',
    category: 'NON_TECHNICAL',
    clearance_level: 'ALL',
    team_size_min: 1,
    team_size_max: 2,
    venue: 'Seminar Hall 2',
    schedule_time: '11:30 AM - 01:00 PM',
    duration: '90 Mins',
    description: 'Strategic board, logic and rapid deduction',
    status: 'AVAILABLE',
  },
  {
    id: 'plot-twist',
    code: '08',
    mission_name: 'PLOT TWIST',
    title: 'Plot Twist',
    event_type: 'NON_TECH',
    category: 'NON_TECHNICAL',
    clearance_level: 'ALL',
    team_size_min: 1,
    team_size_max: 2,
    venue: 'Drawing Hall 1',
    schedule_time: '02:00 PM - 03:30 PM',
    duration: '90 Mins',
    description: 'Creative mystery & impromptu scenario solving',
    status: 'AVAILABLE',
  },
  {
    id: 'short-flim',
    code: '09',
    mission_name: 'SHORT FILM',
    title: 'Short Film',
    event_type: 'NON_TECH',
    category: 'NON_TECHNICAL',
    clearance_level: 'ALL',
    team_size_min: 1,
    team_size_max: 2,
    venue: 'Main Media Center',
    schedule_time: '10:00 AM - 01:00 PM',
    duration: '180 Mins',
    description: 'Filmmaking & cinematic storytelling',
    status: 'AVAILABLE',
  }
];

export const MOCK_TEAMS: Team[] = [
  {
    team_id: 'TEAM-001',
    team_name: 'CyberKnights',
    college: 'PSG College of Technology',
    department: 'Computer Science and Engineering',
    year: 'III Year',
    registered_events: ['ev-hackathon-01', 'ev-quiz-03'],
    payment_status: 'PAID',
    created_at: '2026-09-01T10:00:00Z',
  },
  {
    team_id: 'TEAM-002',
    team_name: 'ByteBusters',
    college: 'Coimbatore Institute of Technology',
    department: 'Information Technology',
    year: 'II Year',
    registered_events: ['ev-debug-02', 'ev-hunt-04'],
    payment_status: 'PAID',
    created_at: '2026-09-01T11:00:00Z',
  },
  {
    team_id: 'TEAM-003',
    team_name: 'ApexStrikerz',
    college: 'Government College of Technology',
    department: 'Electronics & Communication',
    year: 'IV Year',
    registered_events: ['ev-gaming-05'],
    payment_status: 'PAID',
    created_at: '2026-09-01T12:00:00Z',
  }
];

export const MOCK_TEAM_MEMBERS: TeamMember[] = [
  {
    id: 'MEM-001',
    user_id: 'USR-ARUN-001',
    team_id: 'TEAM-001',
    name: 'Arun Kumar',
    email: 'arun.k@psgtech.edu',
    phone: '9876543210',
    is_leader: true,
    passport_token: 'PASSPORT-ARUN-8899',
    passport_issued_at: '2026-09-02T10:00:00Z',
    passport_status: 'ISSUED',
  },
  {
    id: 'MEM-002',
    user_id: 'USR-SNEHA-002',
    team_id: 'TEAM-001',
    name: 'Sneha R',
    email: 'sneha.r@psgtech.edu',
    phone: '9876543211',
    is_leader: false,
    passport_token: 'PASSPORT-SNEHA-7744',
    passport_issued_at: '2026-09-02T10:05:00Z',
    passport_status: 'ISSUED',
  },
  {
    id: 'MEM-003',
    user_id: 'USR-VIKRAM-003',
    team_id: 'TEAM-002',
    name: 'Vikram S',
    email: 'vikram.cit@gmail.com',
    phone: '9876543212',
    is_leader: true,
    passport_token: 'PASSPORT-VIKRAM-3322',
    passport_issued_at: '2026-09-02T10:10:00Z',
    passport_status: 'ISSUED',
  },
  {
    id: 'MEM-004',
    user_id: 'USR-POOJA-004',
    team_id: 'TEAM-003',
    name: 'Pooja Mohan',
    email: 'pooja.gct@gmail.com',
    phone: '9876543213',
    is_leader: true,
    passport_token: 'PASSPORT-POOJA-9911',
    passport_issued_at: '2026-09-02T10:15:00Z',
    passport_status: 'ISSUED',
  }
];

export const MOCK_EVENT_REGISTRATIONS: EventRegistration[] = [
  { id: 'reg-01', reg_id: 1001, team_id: 'TEAM-001', event_id: 'debugging', event_code: '01', user_id: 'USR-ARUN-001', team_name: 'CyberKnights' },
  { id: 'reg-02', reg_id: 1002, team_id: 'TEAM-001', event_id: 'lost-at-sql', event_code: '03', user_id: 'USR-SNEHA-002', team_name: 'CyberKnights' },
  { id: 'reg-03', reg_id: 1003, team_id: 'TEAM-002', event_id: 'debugging', event_code: '01', user_id: 'USR-VIKRAM-003', team_name: 'ByteBusters' },
  { id: 'reg-04', reg_id: 1004, team_id: 'TEAM-002', event_id: 'borderland-at-gcee', event_code: '06', user_id: 'USR-VIKRAM-003', team_name: 'ByteBusters' },
  { id: 'reg-05', reg_id: 1005, team_id: 'TEAM-003', event_id: 'short-flim', event_code: '09', user_id: 'USR-POOJA-004', team_name: 'ApexStrikerz' },
];

export const MOCK_INITIAL_ATTENDANCE: AttendanceRecord[] = [
  {
    id: 'att-01',
    team_id: 'TEAM-001',
    member_id: 'MEM-001',
    user_id: 'USR-ARUN-001',
    participant_name: 'Arun Kumar',
    college: 'PSG College of Technology',
    checkin_type: 'ENTRY',
    event_id: null,
    event_code: null,
    event_name: null,
    scanned_by: 'Karthik Raja (Gate Check-in Staff)',
    scanned_by_id: 'usr-gate-08',
    location: 'Main Gate Arch',
    passport_token_used: 'PASSPORT-ARUN-8899',
    scanned_at: '2026-09-04T09:15:00Z',
  },
  {
    id: 'att-02',
    team_id: 'TEAM-001',
    member_id: 'MEM-002',
    user_id: 'USR-SNEHA-002',
    participant_name: 'Sneha R',
    college: 'PSG College of Technology',
    checkin_type: 'FOOD',
    event_id: null,
    event_code: null,
    event_name: null,
    scanned_by: 'Suresh Babu (Food Committee Head)',
    scanned_by_id: 'usr-food-06',
    location: 'Dining Hall Counter B',
    passport_token_used: 'PASSPORT-SNEHA-7744',
    scanned_at: '2026-09-04T12:45:00Z',
  }
];
